project:
  type: website
  output-dir: docs

website:
  page-navigation: false
  title: "Ondřej Mottl"
  description: "Personal website of Ondřej Mottl, Faculty of Science, Charles University."

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  repo-url: "https://github.com/OndrejMottl/OndrejMottl.github.io"
  favicon: about_me/img/Ondrej_Mottl-transparent-noshadow.png
  image: about_me/img/Ondrej_Mottl-transparent-noshadow.png 

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      - text: "Laboratory of Quantitative Ecology"
        href: lab/about_the_lab.qmd
      
      - text: "Overview of projects"
        href: projects/index.qmd

      - text: "Teaching"
        href: teaching/teaching.qmd
      
      - section: "About me"
        contents:
          - text: "CV"
            href: about_me/cv.qmd
          - text: "List of publications"
            href: about_me/list_of_publications.qmd

      - section: "Work with me"
        contents:
          - text: "Get in touch!"
            href: collaboration/get_in_touch.qmd
          - text: "Collaboration guide"
            href: collaboration/collaboration_guide.qmd
          - text: "Code Convention"
            href: collaboration/code_convention.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2


